name: Git CTF Level 2 Validator
on: [push, workflow_dispatch]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: true # This wipes the workspace to prevent "ghost" files

      - name: Run Validator
        run: |
          chmod +x validate.sh
          ./validate.sh
