name: Git CTF Level 2 Validator
on: [push, workflow_dispatch]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          # fetch-depth 0 fetches all branches and tags
          fetch-depth: 0 

      - name: Make Validator Executable
        run: chmod +x validate.sh

      - name: Run Level 2 Validation
        run: ./validate.sh
